// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
    "enabled": boolean;
    "serverAddress": string;
    "serverPort": number;
    "serverLogin": string;
    "serverPassword": string;
}
