// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "./internal/state/models.js";

export function AutoStartProxy(): $CancellablePromise<void> {
    return $Call.ByID(3263395337);
}

export function GetLocalAddress(): $CancellablePromise<string> {
    return $Call.ByID(1212054027);
}

export function GetSettings(): $CancellablePromise<state$0.Settings | null> {
    return $Call.ByID(3018893939);
}

export function IsProxyRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(697260457);
}

export function SaveSettings(settings: state$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(3784651466, settings);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3487267257, app);
}

export function StartProxy(): $CancellablePromise<void> {
    return $Call.ByID(2746353326);
}

export function StopProxy(): $CancellablePromise<void> {
    return $Call.ByID(1140884718);
}
