// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../../log/slog/models.js";

export interface App {
    /**
     * Manager pattern for organized API
     */
    "Window": WindowManager | null;
    "ContextMenu": ContextMenuManager | null;
    "KeyBinding": KeyBindingManager | null;
    "Browser": BrowserManager | null;
    "Env": EnvironmentManager | null;
    "Dialog": DialogManager | null;
    "Event": EventManager | null;
    "Menu": MenuManager | null;
    "Screen": ScreenManager | null;
    "Clipboard": ClipboardManager | null;
    "SystemTray": SystemTrayManager | null;
    "Logger": slog$0.Logger | null;
}

/**
 * BrowserManager manages browser-related operations
 */
export interface BrowserManager {
}

/**
 * ClipboardManager manages clipboard operations
 */
export interface ClipboardManager {
}

/**
 * ContextMenuManager manages all context menu operations
 */
export interface ContextMenuManager {
}

/**
 * DialogManager manages dialog-related operations
 */
export interface DialogManager {
}

/**
 * EnvironmentManager manages environment-related operations
 */
export interface EnvironmentManager {
}

/**
 * EventManager manages event-related operations
 */
export interface EventManager {
}

/**
 * KeyBindingManager manages all key binding operations
 */
export interface KeyBindingManager {
}

/**
 * MenuManager manages menu-related operations
 */
export interface MenuManager {
}

export interface ScreenManager {
}

/**
 * SystemTrayManager manages system tray-related operations
 */
export interface SystemTrayManager {
}

/**
 * WindowManager manages all window-related operations
 */
export interface WindowManager {
}
